-- WeatherBHN - BHN Overall Scorecard
-- High level BHN signal performance summary. Shows total recommendations,
-- win rate, P&L, and how BHN compares to simply following the market.
-- Headline number: is BHN actually adding value over the market?
-- Populates after settlement reconciler runs nightly at 15:00 UTC.
-- Source: WeatherBHN_Performance_Queries.txt (June 12, 2026) — Query 19
-- Tab: FORMULA/MODELS — PIN at top
--
-- UPDATED 2026-07-02: weather_model_accuracy retired, replaced by
-- weather_gold_contract_ledger (see project memory
-- weather-gold-edge-sheet-retired). Compat CTE below aliases every old
-- column; market_was_correct, bhn_position_taken, bhn_position_side, and
-- accuracy_score have no direct equivalent and are derived.
--
-- FIXED 2026-07-02: found (not a dashboard bug — a data-provenance issue).
-- 48 BET_NO rows carry an identical flat stake_usd=125.0 (zero variance)
-- instead of genuine Kelly sizing, and 90 BET_YES rows predate the current
-- pipeline's action space entirely (cp4_kelly_sizer.py never writes
-- BET_YES, only BET_NO/SKIP). Both are legacy/pre-CP4 data. Several of the
-- flat-stake rows also had market_implied_prob clamped at the 0.99
-- tick-size boundary, generating $271,191.73 of a then-$343,894.13
-- reported PnL (79%) via a legitimate-but-flat-staked 99x payout
-- multiplier.
--
-- PERMANENT FIX 2026-07-02: Fletch decided to exclude both legacy
-- populations permanently rather than backfill/reconstruct them. Rather
-- than re-deriving the exclusion condition per-query, migration
-- sql/migrations/2026-07-02-ledger-exclude-legacy-rows.sql added an
-- is_legacy_row column to weather_gold_contract_ledger and created
-- weather_gold_contract_ledger_performance, a view with legacy rows
-- already filtered out. This CTE now reads from that view — no ad-hoc
-- WHERE filter needed here or in any future dashboard on this table.
--
-- SEPARATE FINDING (not fixed here, flagged for Fletch): bhn_win_rate_pct's
-- denominator is COUNT(*) over ALL rows including SKIP (bhn_correct is
-- always NULL for skips, diluting the rate). Post-legacy-exclusion, this
-- card will currently show near-zero settled data — the only remaining
-- BET_NO rows are freshly generated by the live pipeline (post the
-- write_to_ledger() dry_run fix, also 2026-07-02) and haven't settled yet.
-- That's the honest, expected state of a genuinely clean track record
-- starting from scratch, not a bug.
WITH weather_model_accuracy AS (
    SELECT
        contract_ticker                                        AS contract_id,
        contract_ticker                                        AS contract_title,
        city                                                   AS region,
        contract_side                                          AS variable,
        calibrated_prob                                        AS bhn_predicted_probability,
        market_implied_prob                                    AS market_implied_probability,
        edge,
        (recommended_action IN ('BET_YES', 'BET_NO'))          AS bhn_position_taken,
        stake_usd                                              AS bhn_position_value,
        CASE
            WHEN recommended_action = 'BET_YES' THEN 'yes'
            WHEN recommended_action = 'BET_NO'  THEN 'no'
        END                                                    AS bhn_position_side,
        contract_resolved_yes                                  AS actual_outcome,
        bhn_correct                                            AS bhn_was_correct,
        (market_implied_prob >= 0.5) = contract_resolved_yes   AS market_was_correct,
        paper_pnl                                              AS pnl_dollar,
        outcome_edge_realized                                  AS accuracy_score,
        settled_at                                             AS resolved_at,
        signal_generated_at                                    AS created_at
    FROM weather_gold_contract_ledger_performance
)
SELECT
    -- Volume
    COUNT(*)                                           AS total_recommendations,
    COUNT(*) FILTER (WHERE bhn_position_taken = true) AS trades_placed,
    COUNT(*) FILTER (WHERE bhn_position_taken = false) AS signals_skipped,

    -- BHN accuracy
    COUNT(*) FILTER (WHERE bhn_was_correct = true)    AS bhn_correct,
    COUNT(*) FILTER (WHERE bhn_was_correct = false)   AS bhn_wrong,
    ROUND(
        COUNT(*) FILTER (WHERE bhn_was_correct = true)::numeric
        / NULLIF(COUNT(*), 0) * 100, 1
    )                                                  AS bhn_win_rate_pct,

    -- Market accuracy
    COUNT(*) FILTER (WHERE market_was_correct = true)  AS market_correct,
    ROUND(
        COUNT(*) FILTER (WHERE market_was_correct = true)::numeric
        / NULLIF(COUNT(*), 0) * 100, 1
    )                                                  AS market_win_rate_pct,

    -- BHN vs Market edge
    ROUND(
        (
            COUNT(*) FILTER (WHERE bhn_was_correct = true)::numeric
            / NULLIF(COUNT(*), 0)
            -
            COUNT(*) FILTER (WHERE market_was_correct = true)::numeric
            / NULLIF(COUNT(*), 0)
        ) * 100, 1
    )                                                  AS bhn_vs_market_edge_pct,

    -- P&L
    ROUND(SUM(pnl_dollar), 2)                          AS total_pnl,
    ROUND(AVG(pnl_dollar), 2)                          AS avg_pnl_per_trade,
    ROUND(SUM(pnl_dollar) FILTER (WHERE pnl_dollar > 0), 2) AS total_wins,
    ROUND(SUM(pnl_dollar) FILTER (WHERE pnl_dollar < 0), 2) AS total_losses,

    -- Edge stats
    ROUND(AVG(edge * 100), 1)                          AS avg_edge_pct,
    ROUND(AVG(accuracy_score), 3)                      AS avg_accuracy_score,

    -- Date range
    MIN(resolved_at) AT TIME ZONE 'UTC' AT TIME ZONE 'America/Los_Angeles'
                                                       AS first_reconciled_time_pt,
    MAX(resolved_at) AT TIME ZONE 'UTC' AT TIME ZONE 'America/Los_Angeles'
                                                       AS latest_reconciled_time_pt,
    COUNT(DISTINCT DATE(resolved_at))                  AS trading_days,

    -- Transparency count for the card label — permanently excluded via
    -- weather_gold_contract_ledger_performance, see FIXED note above
    (SELECT COUNT(*) FROM weather_gold_contract_ledger
       WHERE is_legacy_row AND contract_resolved_yes IS NOT NULL)
                                                       AS legacy_rows_excluded

FROM weather_model_accuracy
WHERE actual_outcome IS NOT NULL;
