#!/bin/bash
# BHN (Blackhole Network) — Nightly Diagnostic orchestrator
#
# Runs on LA hub. Collects local status via the per-node
# bhn-status-check.sh collector (deployed to LA at /opt/eh-diagnostics/eh-status-check.sh
# until coordinated migration), combines into one structured log on the
# cold tier, generates a summary, embeds it via the local embedding service,
# and writes a row to the memories table so HORIZON can semantically recall
# operational history.
#
# Designed to be invoked from a systemd timer at 02:00 LA local daily.
# Idempotent — safe to re-run; each run writes its own dated log file and
# its own memory row.
#
# Per the external-observer principle: this script logs ONLY metadata that
# an ISP could already see (service status, byte counts, peer counts, alert
# counts, journal errors). No DNS queries, no pcap, no payloads.

set -uo pipefail

# ---------- Configuration ----------
COLLECTOR=/opt/eh-diagnostics/eh-status-check.sh
LOG_DIR=/mnt/eh-hdd-cold/logs/diagnostics
RUNTIME_LOG=/var/log/eh-diagnostics/eh-nightly-diagnostic.log
DATE_STR=$(date +%Y%m%d)
RUN_TS=$(date '+%Y-%m-%d %H:%M:%S %Z')
REPORT_FILE="$LOG_DIR/eh-status-${DATE_STR}.log"

EMBED_URL='http://127.0.0.1:8001/embed'
PG_DB=eventhorizon

# NJ trading node — reachable via wg0 hub (NJ joined as a peer on LA's existing
# wg0 at <BHN_WG_NJ_IP>/32; NOT on a separate wg2). Tunnel operational since 2026-05-12
# after egress UFW allowlist on LA was patched (both <BHN_NJ_PUBLIC_IP>:51820/udp underlay
# and <BHN_WG_NJ_IP> inner-tunnel rules were needed — see reference_nj_ssh_path memory).
NJ_HOST=<BHN_WG_NJ_IP>           # NJ's wg0 peer IP (on LA's hub)
NJ_PORT=2222               # sshd port on NJ
NJ_USER=root
NJ_KEY=/root/.ssh/eh_frankfurt   # orchestrator key, filename predates Frankfurt's decommission (2026-05-28) — still valid, in NJ's authorized_keys
NJ_TIMEOUT=15

# Future-proofing — additional remote nodes can be added to this array
# as they're provisioned. Each entry: "name|host|user|ssh_key|timeout|port"
declare -a REMOTE_NODES=(
  "nj|${NJ_HOST}|${NJ_USER}|${NJ_KEY}|${NJ_TIMEOUT}|${NJ_PORT}"
)

# ---------- Setup ----------
mkdir -p "$LOG_DIR" "$(dirname "$RUNTIME_LOG")"
exec >>"$RUNTIME_LOG" 2>&1
echo "==> Nightly diagnostic starting at $RUN_TS"

# Sanity — collector must exist
if [ ! -x "$COLLECTOR" ]; then
  echo "ERROR: collector $COLLECTOR not found or not executable. Aborting."
  exit 2
fi

# ---------- Collect ----------
NODES_COVERED=()

# Header in the report file
{
  echo '======================================================================='
  echo "EH NIGHTLY DIAGNOSTIC — $RUN_TS"
  echo "Generated by: $0"
  echo "Run host: $(hostname)"
  echo '======================================================================='
} > "$REPORT_FILE"

# --- LA section (local) ---
{
  echo
  echo '#######################################################################'
  echo '# LA HUB (local)'
  echo '#######################################################################'
  echo
  bash "$COLLECTOR"
} >> "$REPORT_FILE" 2>&1

NODES_COVERED+=("la")
echo "==> LA section captured"

# --- Remote nodes via SSH ---
for entry in "${REMOTE_NODES[@]}"; do
  IFS='|' read -r NAME HOST USER KEY TMOUT PORT <<< "$entry"
  PORT="${PORT:-22}"

  {
    echo
    echo '#######################################################################'
    echo "# ${NAME^^} ($USER@$HOST:$PORT)"
    echo '#######################################################################'
    echo "Attempt time: $(date -u '+%Y-%m-%d %H:%M:%S %Z')"
    echo "SSH key:      $KEY"
    echo "Connect timeout: 8s; total timeout: ${TMOUT}s"
    echo
  } >> "$REPORT_FILE"

  if [ ! -f "$KEY" ]; then
    echo "==> Skipping $NAME: SSH key $KEY missing"
    echo "*** SKIPPED: SSH key $KEY not found on LA — cannot reach $NAME ***" >> "$REPORT_FILE"
    continue
  fi

  # ---- Stage 1: SSH probe ----
  # Isolates "can we even SSH" from "did the collector run". A bare `echo` over SSH
  # exercises auth, network path, sshd config, and remote shell startup without
  # depending on anything in the collector script.
  echo "==> Probing SSH to $NAME ($USER@$HOST:$PORT)..."
  PROBE_OUT=$(timeout 12 ssh \
      -i "$KEY" \
      -p "$PORT" \
      -o StrictHostKeyChecking=accept-new \
      -o ConnectTimeout=8 \
      -o BatchMode=yes \
      -o LogLevel=ERROR \
      "$USER@$HOST" \
      'echo "SSH_PROBE_OK on $(uname -n) kernel $(uname -r) at $(date -u +%H:%M:%S)"' 2>&1)
  PROBE_EXIT=$?

  {
    echo "--- Stage 1: SSH probe (exit $PROBE_EXIT) ---"
    echo "$PROBE_OUT"
    echo
  } >> "$REPORT_FILE"

  if [ $PROBE_EXIT -ne 0 ] || ! echo "$PROBE_OUT" | grep -q SSH_PROBE_OK; then
    echo "==> $NAME PROBE FAILED (ssh exit $PROBE_EXIT)"
    {
      echo "*** SSH PROBE FAILED for $NAME at $RUN_TS — abandoning collector run ***"
      echo "*** Diagnosis hints:"
      echo "***   - ssh exit 124 → timeout (host unreachable on $HOST:$PORT)"
      echo "***   - ssh exit 255 → connection refused / DNS / hostkey / network unreachable"
      echo "***   - 'Permission denied' in probe output → key not in remote authorized_keys, or PasswordAuth required"
      echo "***   - 'Connection refused' → sshd not listening on port $PORT"
    } >> "$REPORT_FILE"
    continue
  fi

  # ---- Stage 2: Run the collector over SSH ----
  # Pipe the LA-side collector script via stdin to remote bash -s. Keeps the
  # collector versioned only on LA — the remote runs whatever LA's master copy
  # says, no sync drift.
  echo "==> $NAME probe OK, piping collector..."
  echo "--- Stage 2: COLLECTOR OUTPUT ($NAME) ---" >> "$REPORT_FILE"

  timeout "$TMOUT" ssh \
      -i "$KEY" \
      -p "$PORT" \
      -o StrictHostKeyChecking=accept-new \
      -o ConnectTimeout=8 \
      -o BatchMode=yes \
      -o LogLevel=ERROR \
      "$USER@$HOST" \
      'bash -s' < "$COLLECTOR" >> "$REPORT_FILE" 2>&1
  COLLECTOR_EXIT=$?

  echo "--- Stage 2 end: collector exit $COLLECTOR_EXIT ---" >> "$REPORT_FILE"

  if [ $COLLECTOR_EXIT -eq 0 ]; then
    NODES_COVERED+=("$NAME")
    echo "==> $NAME section captured (collector exit 0)"
  else
    echo "==> $NAME COLLECTOR FAILED (exit $COLLECTOR_EXIT)"
    {
      echo ""
      echo "*** COLLECTOR FAILED for $NAME — exit $COLLECTOR_EXIT at $RUN_TS ***"
      echo "*** SSH probe passed but 'bash -s < collector' failed."
      echo "*** Reproduce manually on LA:"
      echo "***   ssh -i $KEY -p $PORT -o BatchMode=yes $USER@$HOST 'bash -s' < $COLLECTOR | head -50"
      echo "*** Common causes: collector references binary not on remote (suricata, crowdsec, eh-embed are LA-only),"
      echo "*** remote bash version too old for the collector's syntax, or remote disk full."
    } >> "$REPORT_FILE"
  fi
done

# Footer
{
  echo
  echo '======================================================================='
  echo "DIAGNOSTIC COMPLETE — $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo "Nodes covered: ${NODES_COVERED[*]}"
  echo "Log: $REPORT_FILE"
  echo '======================================================================='
} >> "$REPORT_FILE"

echo "==> Report file: $REPORT_FILE ($(wc -l < "$REPORT_FILE") lines)"

# ---------- Summary generation ----------
# Pull key metrics from Postgres directly so the summary reflects ground
# truth, not just what the collector logged. The collector's output is the
# detailed forensic record; the summary is HORIZON's searchable abstract.

LA_KERNEL=$(uname -r)
LA_UPTIME=$(uptime -p 2>/dev/null || uptime)
LA_LOAD=$(awk '{print $1, $2, $3}' /proc/loadavg)

# Service health: count anything not active
SERVICES_DOWN=0
for svc in postgresql wg-quick@wg0 docker eh-embed dnscrypt-proxy fail2ban; do
  if ! systemctl is-active --quiet "$svc" 2>/dev/null; then
    SERVICES_DOWN=$((SERVICES_DOWN + 1))
  fi
done

# n8n container check
N8N_STATE=$(docker ps --filter name=n8n --format '{{.Status}}' 2>/dev/null | head -1)
[ -z "$N8N_STATE" ] && N8N_STATE='not running'

# WireGuard peer count
WG_PEERS=$(wg show all peers 2>/dev/null | wc -l)

# Pull recent stats from Postgres (24h security event volume + open anomalies)
PG_STATS=$(sudo -u postgres psql -d "$PG_DB" -At -F '|' -c "
SELECT
  (SELECT COUNT(*) FROM security_events WHERE detected_at > NOW() - INTERVAL '24 hours'),
  (SELECT COUNT(*) FROM security_events WHERE detected_at > NOW() - INTERVAL '24 hours' AND severity = 'high'),
  (SELECT COUNT(*) FROM security_events WHERE detected_at > NOW() - INTERVAL '24 hours' AND severity = 'critical'),
  (SELECT COUNT(*) FROM anomalies WHERE resolved = FALSE),
  (SELECT COUNT(*) FROM sessions WHERE disconnected_at IS NULL),
  (SELECT COUNT(DISTINCT user_key) FROM sessions WHERE connected_at > NOW() - INTERVAL '24 hours');
" 2>/dev/null | tr -d ' ')
IFS='|' read -r SEC_TOTAL SEC_HIGH SEC_CRIT ANOM_OPEN SESS_OPEN USERS_24H <<< "${PG_STATS:-0|0|0|0|0|0}"

# Top 3 hostile source IPs in last 24h
TOP_IPS=$(sudo -u postgres psql -d "$PG_DB" -At -c "
SELECT string_agg(source_ip || '(' || cnt || ')', ', ')
FROM (
  SELECT source_ip, COUNT(*) AS cnt
  FROM security_events
  WHERE detected_at > NOW() - INTERVAL '24 hours'
  GROUP BY source_ip
  ORDER BY cnt DESC
  LIMIT 3
) sub;
" 2>/dev/null)
[ -z "$TOP_IPS" ] && TOP_IPS='(none)'

# Disk pressure
NVME_PCT=$(df --output=pcent /mnt/eh-nvme-hot 2>/dev/null | tail -1 | tr -d ' %')
[ -z "$NVME_PCT" ] && NVME_PCT=0
HDD_PCT=$(df --output=pcent /mnt/eh-hdd-cold 2>/dev/null | tail -1 | tr -d ' %')
[ -z "$HDD_PCT" ] && HDD_PCT=0

# Status verdict — green/yellow/red
STATUS_VERDICT='green'
IMPORTANCE=3
NOTABLE=()
if [ "$SERVICES_DOWN" -gt 0 ]; then
  STATUS_VERDICT='red'; IMPORTANCE=9
  NOTABLE+=("$SERVICES_DOWN core service(s) inactive")
fi
if [ "$ANOM_OPEN" -gt 0 ]; then
  [ "$STATUS_VERDICT" = 'green' ] && STATUS_VERDICT='yellow'
  IMPORTANCE=$(( IMPORTANCE > 6 ? IMPORTANCE : 6 ))
  NOTABLE+=("$ANOM_OPEN open anomalies")
fi
if [ "$SEC_CRIT" -gt 0 ]; then
  STATUS_VERDICT='red'; IMPORTANCE=$(( IMPORTANCE > 8 ? IMPORTANCE : 8 ))
  NOTABLE+=("$SEC_CRIT critical security events")
fi
if [ "$NVME_PCT" -gt 80 ] || [ "$HDD_PCT" -gt 80 ]; then
  [ "$STATUS_VERDICT" = 'green' ] && STATUS_VERDICT='yellow'
  IMPORTANCE=$(( IMPORTANCE > 5 ? IMPORTANCE : 5 ))
  NOTABLE+=("disk pressure (NVMe ${NVME_PCT}%, HDD ${HDD_PCT}%)")
fi

NOTABLE_STR='nothing notable'
if [ "${#NOTABLE[@]}" -gt 0 ]; then
  NOTABLE_STR=$(IFS='; '; echo "${NOTABLE[*]}")
fi

# Build the natural-language summary HORIZON will embed and recall
SUMMARY=$(cat <<EOF
EH nightly diagnostic ${DATE_STR}. Status: ${STATUS_VERDICT}. LA hub kernel ${LA_KERNEL}, ${LA_UPTIME}, load ${LA_LOAD}. n8n container: ${N8N_STATE}. ${SERVICES_DOWN} services down. WireGuard peers: ${WG_PEERS} configured. Last 24h: ${SEC_TOTAL} security events (${SEC_HIGH} high, ${SEC_CRIT} critical), ${USERS_24H} distinct users connected, ${SESS_OPEN} sessions currently open. Top hostile sources: ${TOP_IPS}. Open anomalies: ${ANOM_OPEN}. Disk: NVMe ${NVME_PCT}%, HDD ${HDD_PCT}%. Notable: ${NOTABLE_STR}. Nodes covered: ${NODES_COVERED[*]}.
EOF
)

echo "==> Summary built ($(echo "$SUMMARY" | wc -c) chars)"
echo "$SUMMARY" >> "$RUNTIME_LOG"

# ---------- Embed ----------
EMBED_PAYLOAD=$(jq -c -n --arg t "$SUMMARY" '{text:$t}')
EMBED_RESPONSE=$(curl -sS -m 10 -X POST "$EMBED_URL" \
  -H 'Content-Type: application/json' \
  -d "$EMBED_PAYLOAD" 2>>"$RUNTIME_LOG")

if [ -z "$EMBED_RESPONSE" ]; then
  echo "ERROR: embed service did not respond. Skipping memories INSERT."
  exit 3
fi

VECTOR=$(echo "$EMBED_RESPONSE" | jq -r '.vector | @json' 2>/dev/null)
VEC_DIM=$(echo "$EMBED_RESPONSE" | jq -r '.vector | length' 2>/dev/null)

if [ "$VEC_DIM" != '384' ]; then
  echo "ERROR: embed returned dim=$VEC_DIM (expected 384). Skipping INSERT."
  exit 4
fi

# Strip surrounding quotes from @json output so we can interpolate as pgvector literal
VECTOR_LITERAL="${VECTOR}"
echo "==> Vector OK (384 dims)"

# ---------- Insert into memories ----------
TAGS_JSON=$(printf '"%s",' "diagnostic" "nightly" "$(date +%Y-%m-%d)" "${NODES_COVERED[@]}")
TAGS_JSON="{${TAGS_JSON%,}}"  # postgres array literal

METADATA=$(jq -c -n \
  --arg verdict "$STATUS_VERDICT" \
  --argjson sec_total "${SEC_TOTAL:-0}" \
  --argjson sec_high "${SEC_HIGH:-0}" \
  --argjson sec_crit "${SEC_CRIT:-0}" \
  --argjson anom_open "${ANOM_OPEN:-0}" \
  --argjson sess_open "${SESS_OPEN:-0}" \
  --argjson users_24h "${USERS_24H:-0}" \
  --argjson services_down "${SERVICES_DOWN:-0}" \
  --argjson nvme_pct "${NVME_PCT:-0}" \
  --argjson hdd_pct "${HDD_PCT:-0}" \
  --arg n8n_state "$N8N_STATE" \
  --arg log_path "$REPORT_FILE" \
  '{
    verdict:$verdict,
    sec_total_24h:$sec_total,
    sec_high_24h:$sec_high,
    sec_critical_24h:$sec_crit,
    anomalies_open:$anom_open,
    sessions_open:$sess_open,
    users_24h:$users_24h,
    services_down:$services_down,
    disk_nvme_pct:$nvme_pct,
    disk_hdd_pct:$hdd_pct,
    n8n_state:$n8n_state,
    log_path:$log_path
  }')

# Pass parameters via psql's -v flag (psql variables, referenced as :'VAR'
# in SQL — auto-quoted and escaped). sudo -u strips most env vars, so the
# bash-env approach silently fails. -v survives the sudo boundary.
TITLE="Nightly diagnostic $(date +%Y-%m-%d)"

sudo -u postgres psql -d "$PG_DB" -v ON_ERROR_STOP=1 \
  -v "EH_TITLE=$TITLE" \
  -v "EH_CONTENT=$SUMMARY" \
  -v "EH_VECTOR=$VECTOR_LITERAL" \
  -v "EH_TAGS=$TAGS_JSON" \
  -v "EH_META=$METADATA" \
  -v "EH_IMP=$IMPORTANCE" \
  <<'SQL'
INSERT INTO memories (memory_type, title, content, embedding, source, tags, importance, metadata)
VALUES (
  'observation',
  :'EH_TITLE',
  :'EH_CONTENT',
  (:'EH_VECTOR')::vector,
  'eh-nightly-diagnostic',
  (:'EH_TAGS')::text[],
  (:'EH_IMP')::smallint,
  (:'EH_META')::jsonb
)
RETURNING id;
SQL
PGEXIT=$?

if [ "$PGEXIT" -eq 0 ]; then
  echo "==> Memory row inserted"
else
  echo "ERROR: psql INSERT failed with exit $PGEXIT"
  exit 5
fi

# ---------- Retention housekeeping ----------
# Keep daily logs forever on cold tier (they're small text files), but log
# the size so we can monitor growth.
TOTAL_SIZE=$(du -sh "$LOG_DIR" 2>/dev/null | awk '{print $1}')
echo "==> Log dir size: $TOTAL_SIZE"

echo "==> Nightly diagnostic complete at $(date '+%Y-%m-%d %H:%M:%S %Z')"
exit 0
